### ISSUE TITLE
Training run swin module error

### ISSUE THREAD

**Issue by Him-wen** [cv516Buaa/tph-yolov5#9]
May I ask the author why this is? Without modifying any code, use the training code: python train.py --img 1536 --adam --batch 4 --epochs 80 --data ./data/VisDrone.yaml --weights yolov5l.pt --hy data/hyps /hyp.VisDrone.yaml --cfg models/yolov5l-xs-tph.yaml --name v5l-xs-tph
Error message：

Traceback (most recent call last):
  File "train.py", line 630, in <module>
    main(opt)
  File "train.py", line 527, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 119, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/root/autodl-tmp/tph-yolov5-main/models/yolo.py", line 104, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/root/autodl-tmp/tph-yolov5-main/models/yolo.py", line 291, in parse_model
    m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
  File "/root/autodl-tmp/tph-yolov5-main/models/common.py", line 493, in __init__
    self.m = SwinTransformerBlock(c_, c_, c_//32, n)
  File "/root/autodl-tmp/tph-yolov5-main/models/common.py", line 426, in __init__
    self.tr = nn.Sequential(*(SwinTransformerLayer(c2, num_heads=num_heads, window_size=window_size,  shift_size=0 if (i % 2 == 0) else self.shift_size ) for i in range(num_layers)))
  File "/root/autodl-tmp/tph-yolov5-main/models/common.py", line 426, in <genexpr>
    self.tr = nn.Sequential(*(SwinTransformerLayer(c2, num_heads=num_heads, window_size=window_size,  shift_size=0 if (i % 2 == 0) else self.shift_size ) for i in range(num_layers)))
  File "/root/autodl-tmp/tph-yolov5-main/models/common.py", line 338, in __init__
    self.attn = WindowAttention(
  File "/root/autodl-tmp/tph-yolov5-main/models/common.py", line 259, in __init__
    coords = torch.stack(torch.meshgrid([coords_h, coords_w], indexing="ij"))  # [2, Mh, Mw]
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

**Comment by cv516Buaa** [comment]
You can refer to https://github.com/numpy/numpy/issues/7130

**Comment by Him-wen** [comment]
thanks

**Comment by cwlinghk** [comment]
> You can refer to [numpy/numpy#7130](https://github.com/numpy/numpy/issues/7130)

I guess the error is due to pytorch's meshgrid instead of numpy's meshgrid,
see
https://github.com/pytorch/pytorch/issues/50276
